---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachines.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domain.uuid
    name: UUID
    type: string
  - JSONPath: .spec.running
    name: STATUS
    type: boolean
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.image
    name: IMAGE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
    - vm
    - vms
    singular: virtualmachine
  scope: Namespaced
  version: v1alpha3
