apiVersion: v1
kind: Namespace
metadata:
   name: cloudplus
   labels:
     name: cloudplus
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubevirt-controller-manager
  namespace: cloudplus
  labels:
    app: kubevirt-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-controller-manager
  template:
    metadata:
      labels:
        app: kubevirt-controller-manager
    spec:
      hostNetwork: true
      containers:
      - image: github.com/kubevirt-controller-manager:v1.14.1
        imagePullPolicy: IfNotPresent
        name: kubevirt-controller-manager
        command: [ "java", "-jar", "kubevirt-convertor-2.0.0-SNAPSHOT-jar-with-dependencies.jar" ]
        volumeMounts:
        - name: admin
          mountPath: /etc/kubernetes
      volumes:
      - name: admin
        hostPath:
          path: /etc/kubernetes
