apiVersion: v1
kind: Node
metadata:
  annotations:
    flannel.alpha.coreos.com/backend-data: '{"VtepMAC":"8a:b8:22:b4:72:66"}'
    flannel.alpha.coreos.com/backend-type: vxlan
    flannel.alpha.coreos.com/kube-subnet-manager: "true"
    node.alpha.kubernetes.io/ttl: "0"
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    k8s-app: fluentd
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: mocker
    kubernetes.io/os: linux
    node-role.kubernetes.io/slave: ""
    registry: registry
  name: mocker
spec:
  podCIDR: 192.192.0.0/24
