apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kubevirt-controller-manager
  namespace: cloudplus
  labels:
    app: kubevirt-controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubevirt-controller-manager
  template:
    metadata:
      labels:
        app: kubevirt-controller-manager
    spec:
      hostNetwork: true
      containers:
      - image: registry.cn-hangzhou.aliyuncs.com/cloudplus-lab/kubevirt-controller-manager:v1.14.1
        imagePullPolicy: IfNotPresent
        name: kubevirt-controller-manager
        command: [ "java", "-jar", "kubevirt-controller-2.0.0-SNAPSHOT-jar-with-dependencies.jar" ]
        volumeMounts:
        - name: admin
          mountPath: /etc/kubernetes
      volumes:
      - name: admin
        hostPath:
          path: /etc/kubernetes
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    kubevirt.io: ""
  name: kubevirt-controller-role
rules:
- apiGroups: ["apiextensions.k8s.io"]
  resources: ["customresourcedefinitions"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["cloudplus.io"]
  resources: ["virtualmachines"]
  verbs: ["get", "list", "watch", "create", "delete"]  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubevirt-controller-rolebinding
  namespace: cloudplus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubevirt-controller-role
subjects:
- kind: Group
  name: system:serviceaccounts:cloudplus
  apiGroup: rbac.authorization.k8s.io
