---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  labels:
    kubevirt.io: ""
  name: virtualmachines.cloudplus.io
spec:
  additionalPrinterColumns:
  - JSONPath: .spec.domain.uuid.text
    name: UUID
    type: string
  - JSONPath: .spec.domain._type
    name: TYPE
    type: string
  - JSONPath: .spec.domain.vcpu.text
    name: CPU
    type: string
  - JSONPath: .spec.domain.memory.text
    name: RAM(KB)
    type: string
  - JSONPath: .status.phase
    name: STATUS
    type: string
  - JSONPath: .metadata.creationTimestamp
    name: AGE
    type: date
  - JSONPath: .spec.nodeName
    name: NODE
    type: string
  - JSONPath: .spec.image
    name: IMAGE
    type: string
  group: cloudplus.io
  names:
    kind: VirtualMachine
    plural: virtualmachines
    shortNames:
    - vm
    - vms
    singular: virtualmachine
  scope: Cluster
  version: v1alpha3
